### ISSUE TITLE
Install MSYS to build ruby native extensions.

### ISSUE THREAD

**Issue by juliusgb** [juliusgb/dev-laptop-setup#9]
Without msys, building native extensions for ruby gems fails. E.g., for `http_parser.rb`

Remove comment from https://github.com/juliusgb/dev-laptop-setup/blob/main/packer/template.pkr.hcl#L159 to install it.

On fresh jekyll site, run `bundle install`, I get
```
In Gemfile:
  jekyll-feed was resolved to 0.16.0, which depends on
    jekyll was resolved to 4.0.1, which depends on
      em-websocket was resolved to 0.5.3, which depends on
        http_parser.rb
mingw32-make: *** [makefile:5: prep] Error 5
```

Manual isntall of the http_parser gem also fails. 
Command: `/path/to/jekyll-site> gem install http_parser.rb --version 0.6.0`
Output:
```
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing http_parser.rb:
        ERROR: Failed to build gem native extension.
```

Output of `ridk version` doesn't have the title and version as in https://github.com/rubygems/rubygems/issues/977#issuecomment-414073762:
```
---
ruby:
  path: C:/opt/tools/Ruby/3.0.4/x64
  version: 3.0.4
  platform: x64-mingw32
  cc: gcc.exe (Rev10, Built by MSYS2 project) 11.2.0
ruby_installer:
  package_version: 3.0.4-1
  git_commit: 17502f9
msys2:
  path: C:\Program Files\Git
cc: gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.1826]
```
